## Numpy

In [2]:
import numpy as np


## 0 D

In [8]:
a=np.array(23)
print(a)

23


## 1 D

In [ ]:
b=np.array([1,2,4,6,7])
print(b)

In [10]:
b.dtype

dtype('int32')

In [11]:
b.shape

(5,)

In [12]:
b.ndim

1

In [14]:
b.size

5

In [16]:
b[3]

6

In [18]:
b[1]

2

### 2D Array

In [20]:
c=np.array([[2,3,5,6,7],[2,5,7,9,0]])
print(c)

[[2 3 5 6 7]
 [2 5 7 9 0]]


In [22]:
c.dtype

dtype('int32')

In [23]:
c.size

10

In [24]:
c.shape

(2, 5)

In [25]:
c.ndim

2

In [28]:
c[0]

array([2, 3, 5, 6, 7])

### Multi Demensional Array

In [30]:
d=np.array([[[[[3]]]]])
print(d)

[[[[[3]]]]]


In [32]:
d1=np.array([[[[1,3,5,7]]]])
print(d1)

[[[[1 3 5 7]]]]


In [33]:
d1.shape

(1, 1, 1, 4)

In [34]:
d1.size

4

In [35]:
d1.ndim

4

In [36]:
d1.dtype

dtype('int32')

In [37]:
d1[0][0]

array([[1, 3, 5, 7]])

In [39]:
d1[0]

array([[[1, 3, 5, 7]]])

In [43]:
d2=np.array([[1,2,4,5,6],[3,5,7,8,0]],dtype=float)
print(d2)

[[1. 2. 4. 5. 6.]
 [3. 5. 7. 8. 0.]]


## Filling

In [47]:
a_full = np.full((3,4,12),5)
a_full

array([[[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]]])

In [48]:
a_full.ndim

3

## Zeros and ones

In [58]:
a_zero = np.zeros((3,3))
a_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
a1_ones=np.ones((3,5))
a1_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Empty and Random

In [65]:
e = np.empty((5,5))
e

array([[1.14910268e-311, 7.70742408e-322, 0.00000000e+000,
        0.00000000e+000, 1.33511018e-306],
       [1.15998412e-028, 4.31603868e-080, 1.94919985e-153,
        1.35717430e+131, 7.06743455e-096],
       [7.06743455e-096, 1.81148490e-152, 6.14099335e-071,
        4.57667790e-072, 4.57667790e-072],
       [6.01391519e-154, 7.06764512e-096, 7.06743455e-096,
        7.19081964e+140, 4.99874708e+217],
       [4.47303447e-143, 1.46899974e+179, 9.08367237e+223,
        1.16466228e-028, 1.03775656e-314]])

In [69]:
rand=np.random.random((2,4))
rand

array([[0.32904066, 0.73102497, 0.50589836, 0.25831331],
       [0.90662306, 0.2157078 , 0.71543991, 0.83790552]])